// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jqspbjdaafjunhmkxzwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impxc3BiamRhYWZqdW5obWt4endrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5MDAzNTMsImV4cCI6MjA2MjQ3NjM1M30.vRhpgYZbL92ZPpJvjJFGhFdnXOA_qYtcIBNlEmTLYCQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);